#!/usr/bin/env bash
# Cross-chain proof for the OTHER core_kms capability: hybrid (X25519 +
# ML-KEM-768) encryption, not signing. Unlike the signing proof, no oracle
# and no enforcement-model classification is needed at all — confidentiality
# is bilateral, so the chain only ever carries opaque bytes it cannot read.
# Recipient's encryption keys are generated by core_kms; the sender encrypts
# off-chain; Anvil just stores/relays the ciphertext bundle; the recipient
# decrypts off-chain via core_kms and recovers the original plaintext.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

export PATH="$HOME/.foundry/bin:$PATH"
JAVA=${JAVA:-/opt/homebrew/opt/openjdk@17/bin/java}
JAR=cli/target/anvil-pqc-cli-jar-with-dependencies.jar
RPC=http://127.0.0.1:8545

SENDER_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

echo "--- starting anvil ---"
anvil > anvil_encryption.log 2>&1 &
ANVIL_PID=$!
trap 'kill $ANVIL_PID 2>/dev/null || true' EXIT
sleep 1

echo "--- deploying PqcConfidentialPayload.sol (no crypto logic at all) ---"
DEPLOY_OUT=$(cd contracts && forge create src/PqcConfidentialPayload.sol:PqcConfidentialPayload \
  --rpc-url $RPC --private-key $SENDER_KEY --broadcast 2>&1)
echo "$DEPLOY_OUT"
CONTRACT=$(echo "$DEPLOY_OUT" | grep "Deployed to:" | awk '{print $3}')
echo "contract: $CONTRACT"

echo ""
echo "--- recipient: generate hybrid encryption keys via core_kms ---"
KEYS=$($JAVA -jar "$JAR" generate-recipient-keys)
X_PUB=$(echo "$KEYS" | sed -n '1p')
KEM_PUB=$(echo "$KEYS" | sed -n '2p')
X_PRIV=$(echo "$KEYS" | sed -n '3p')
KEM_PRIV=$(echo "$KEYS" | sed -n '4p')
echo "recipient X25519 public key: ${#X_PUB} hex chars"
echo "recipient ML-KEM-768 public key: ${#KEM_PUB} hex chars"

PLAINTEXT="confidential trade details: 1000 units @ \$42.50"
echo ""
echo "--- sender: hybrid-encrypt the payload via core_kms (off-chain, bilateral) ---"
ENC=$($JAVA -jar "$JAR" encrypt "$X_PUB" "$KEM_PUB" "$PLAINTEXT")
EPH=0x$(echo "$ENC" | sed -n '1p')
KEMCT=0x$(echo "$ENC" | sed -n '2p')
NONCE=0x$(echo "$ENC" | sed -n '3p')
AESCT=0x$(echo "$ENC" | sed -n '4p')
echo "plaintext:  \"$PLAINTEXT\""
echo "aes ciphertext bytes on-chain: $(( (${#AESCT} - 2) / 2 ))"

echo ""
echo "--- submitting ciphertext bundle to Anvil (chain stores opaque bytes, nothing more) ---"
cast send "$CONTRACT" "submitPayload(bytes,bytes,bytes,bytes)" "$EPH" "$KEMCT" "$NONCE" "$AESCT" \
  --rpc-url $RPC --private-key $SENDER_KEY > /dev/null
echo "submitted."

echo ""
echo "--- anyone can read the bundle off-chain, but cannot decrypt it ---"
cast call "$CONTRACT" "bundles(uint256)(address,bytes,bytes,bytes,bytes)" 0 --rpc-url $RPC | head -1
echo "[the recipient's private keys never touched this chain]"

echo ""
echo "--- recipient: fetch the bundle and decrypt via core_kms (off-chain, bilateral) ---"
READ_BACK=$(cast call "$CONTRACT" "bundles(uint256)(address,bytes,bytes,bytes,bytes)" 0 --rpc-url $RPC)
R_EPH=$(echo "$READ_BACK" | sed -n '2p')
R_KEMCT=$(echo "$READ_BACK" | sed -n '3p')
R_NONCE=$(echo "$READ_BACK" | sed -n '4p')
R_AESCT=$(echo "$READ_BACK" | sed -n '5p')

RECOVERED=$($JAVA -jar "$JAR" decrypt "$X_PRIV" "$KEM_PRIV" "$X_PUB" "$KEM_PUB" \
  "${R_EPH#0x}" "${R_KEMCT#0x}" "${R_NONCE#0x}" "${R_AESCT#0x}")
echo "recovered: \"$RECOVERED\""

if [ "$RECOVERED" = "$PLAINTEXT" ]; then
  echo ""
  echo "PROOF SUCCEEDED: hybrid-encrypted payload, carried as opaque bytes through"
  echo "an EVM chain with zero on-chain cryptography, recovered correctly by the"
  echo "intended recipient via core_kms. No core_kms changes; no chain-specific"
  echo "crypto support required at all."
else
  echo "FAIL: recovered plaintext does not match original"; exit 1
fi
